# Generated by Django 4.1.5 on 2023-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.TextField(choices=[('SNN', 'Sequential Neural Network'), ('RF', 'Random Forests'), ('DNN', 'Deep Neural Network')])),
                ('prediction_type', models.TextField(choices=[('SOL', 'Solubility'), ('EMUL', 'Emulsification')], default='SOL')),
                ('version', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_um', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yield_ml', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_mw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_pi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sequence_length', models.BigIntegerField()),
                ('sequence_mass', models.BigIntegerField()),
                ('gene_product_type', models.TextField()),
                ('solubility', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gene_name', models.TextField()),
                ('cell_location', models.TextField()),
                ('amino_acid_sequence', models.TextField()),
                ('organism', models.TextField()),
            ],
        ),
    ]
