# Generated by Django 4.1.5 on 2023-01-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='version',
            field=models.TextField(null=True),
        ),
    ]
