# Generated by Django 4.1.5 on 2023-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_predictor_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='solubility',
        ),
        migrations.AlterField(
            model_name='predictor',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='amino_acid_sequence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='cell_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='organism',
            field=models.TextField(null=True),
        ),
    ]
