# Generated by Django 4.1.5 on 2023-01-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_protein_solubility_alter_predictor_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='status',
            field=models.TextField(choices=[('NEW', 'Newly Created'), ('TRAINED', 'Trained'), ('TESTED', 'Tested'), ('SAVED', 'Model Saved')], default='NEW'),
        ),
        migrations.AddField(
            model_name='protein',
            name='solubility',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='amino_acid_sequence',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
