# Generated by Django 4.1.5 on 2023-01-14 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_predictor_status_protein_solubility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='slug',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictor',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
