# Generated by Django 4.1.5 on 2023-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_predictor_slug_alter_predictor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
