# Generated by Django 4.1.5 on 2023-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dataset_alter_predictor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='status',
            field=models.TextField(choices=[('NEW', 'Newly Created'), ('UPLOADED', 'Dataset Uploaded'), ('TRAINED', 'Trained'), ('TESTED', 'Tested'), ('SAVED', 'Model Saved')], default='NEW'),
        ),
    ]
