# Generated by Django 4.1.5 on 2023-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_predictor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='batch_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='epochs',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='predictor',
            name='learning_rate',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=12),
        ),
        migrations.AddField(
            model_name='predictor',
            name='seed',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='predictor',
            name='split',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='location',
            field=models.FileField(upload_to='datasets'),
        ),
    ]
