# Generated by Django 4.1.5 on 2023-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_predictor_batch_size_predictor_epochs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='learning_rate',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=12),
        ),
    ]
