# Generated by Django 4.1.5 on 2023-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_predictor_learning_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='mae',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='rmse',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
    ]
