# Generated by Django 4.1.5 on 2023-01-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_predictor_mae_predictor_rmse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='gene_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene_product_type',
            field=models.TextField(null=True),
        ),
    ]
