# Generated by Django 4.1.5 on 2023-01-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_protein_gene_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='location',
        ),
    ]
