# Generated by Django 4.1.5 on 2023-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_predictor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='helix_probability',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='hydrophobicity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='polarizability',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='sheet_probability',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='steric_parameter',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='volume',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='location',
            field=models.FileField(upload_to='resources/public/datasets'),
        ),
    ]
