# Generated by Django 4.1.5 on 2023-01-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_protein_helix_probability_protein_hydrophobicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='pi',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
