# Generated by Django 4.1.5 on 2023-01-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_protein_pi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='pi',
        ),
    ]
