# Generated by Django 4.1.5 on 2023-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_predictor_options_alter_predictor_model_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsembleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predictors', models.ManyToManyField(to='app.predictor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
